account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("", views.account, name="account"),
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
    path("kyc-update/", views.kyc_update, name="kyc-update"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

banking_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userauths.urls')),
    path('', include('core.urls')),
    path('account/', include('account.urls')),
    path('', include('transaction.urls')),
    path('', include('cards.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

transaction/urls.py
from django.urls import path

from .views import (
    transaction_detail,
    transaction_lists
)
from . import payment_request
from .payment_transfer import (search_users_account_number,
                               AmountTransfer,
                               AmountTransferProcess,
                               TransferConfirmation,
                               TransferProcess,
                               TransferCompleted,
                               )


app_name = "transaction"

urlpatterns = [

    # transfer
    path('search_account/', search_users_account_number,
         name='search-account'),
    path("amount-transfer/<account_number>/",
         AmountTransfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/",
         AmountTransferProcess, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/",
         TransferConfirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/",
         TransferProcess, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/",
         TransferCompleted, name="transfer-completed"),


    # transactions
    path("transactions/", transaction_lists, name="transactions"),
    path("transaction-detail/<transaction_id>/",
         transaction_detail, name="transaction-detail"),

    # Payment Request
    path("request-search-account/", payment_request.SearchUsersRequest,
         name="request-search-account"),
    path("amount-request/<account_number>/",
         payment_request.AmountRequest, name="amount-request"),
    path("amount-request-process/<account_number>/",
         payment_request.AmountRequestProcess, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/",
         payment_request.AmountRequestConfirmation,
         name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/",
         payment_request.AmountRequestFinalProcess,
         name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/",
         payment_request.RequestCompleted, name="amount-request-completed"),

    # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/",
         payment_request.settlement_confirmation,
         name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/",
         payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/",
         payment_request.SettlementCompleted, name="settlement-completed"),
    path("delete-request/<transaction_id>/",
         payment_request.deletepaymentrequest, name="delete-request"),


]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.loginView, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>PayPRO - Money Transfer and Online Payments HTML Template</title>

    <link
      rel="shortcut icon"
      href="{% static 'assets/images/fav.png' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/font-awesome.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/plugin/nice-select.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/plugin/magnific-popup.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/plugin/animate.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  </head>

  <body>
    <a href="javascript:void(0)" class="scrollToTop"
      ><i class="fas fa-angle-double-up"></i
    ></a>

    <header class="header-section">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex header-area">
            {% include 'partials/navbar.html'%}
          </div>
          <!-- alert start -->
          {% if messages %} {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <strong>{{ message }}</strong>
          </div>
          {% endfor %} {% endif %}
          <script>
            setTimeout(() => {
              $(".alert").alert("close");
            }, 4000);
          </script>
          <!-- alert end -->
        </div>
      </div>
    </header>
    <!-- header-section end -->

    {% block content %} {% endblock content %}

    <!--==================================================================-->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
                      
    <a class="navbar-brand" href="index.html">
        <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="logo">
    </a>
    
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbar-content">
        <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
     
        <div class="right-area header-action d-flex align-items-center max-un">
            {% if request.user.is_authenticated %}
            <a href="{% url 'account:account' %}" class="login cmdn-btn mx-3 p-2" style="font-size: 25px;" >Account</a>
            <a href="{% url 'account:dashboard' %}" class="login cmdn-btn mx-3 p-2" style="font-size: 25px;">Dasboard</a>
            <a href="{% url 'transaction:transactions' %}" class="login cmdn-btn mx-3 p-2" style="font-size: 25px;">Transactions</a>
            <!-- <a href="/admin" class="login cmdn-btn mx-3 p-2" style="font-size: 25px;">Admin</a> -->
            <a href="{% url 'userauths:sign-out' %}" class="login cmn-btn mx-3 p-2" style="font-size: 25px;">Sign Out</a>
            <div class="head-area d-flex align-items-center">
              <div class="profile-img mx-5">
                <a href="{% url 'account:account' %}" class="profile-link">
                    <img src="{{ user.account.kyc.image.url }}" style="width: 50px; height: 50px;" alt="User">
                </a>
                  <h5>{{ user.account.kyc.full_name }}</h5>
              </div>
          </div>
            
            {% else %}
            <a href="{% url 'userauths:sign-in' %}" class="login cmn-btn " style="font-size: 25px;">Login</a>
            <a href="{% url 'userauths:sign-up' %}" class="cmn-btn mx-3 p-2" style="font-size: 25px;">Sign Up
                <i class="fas fa-caret-right"></i>
            </a>
            <div class="head-area d-flex align-items-center">
              <div class="profile-img mx-5">
                  <img src="" style="width: 50px; height: 50px;" alt="anomous user">
              </div>
          </div>
            {% endif %}
            
        </div>
      
    </div>
</nav>